# Configuration for SwiftLint (https://github.com/realm/SwiftLint)

excluded:
  - .bundle
  - Carthage
  - fastlane

opt_in_rules:
  - all

analyzer_rules:
  - all

disabled_rules:
  - anonymous_argument_in_multiline_closure
  - balanced_xctest_lifecycle
  - contrasted_opening_brace
  - direct_return # TODO: re-enable this rule
  - discouraged_none_name # TODO: re-enable this rule
  - discouraged_optional_collection
  - explicit_acl
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - file_name
  - file_types_order
  - final_test_case # TODO: re-enable this rule
  - for_where # TODO: re-enable this rule
  - function_default_parameter_at_end
  - identifier_name
  - indentation_width
  - legacy_objc_type
  - line_length
  - multiline_arguments # TODO: re-enable this rule
  - multiline_arguments_brackets
  - multiline_call_arguments # TODO: re-enable this rule
  - multiline_parameters # TODO: re-enable this rule
  - multiline_parameters_brackets
  - no_empty_block # TODO: re-enable this rule
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - non_overridable_class_declaration # TODO: re-enable this rule
  - object_literal
  - one_declaration_per_file
  - prefer_condition_list # TODO: re-enable this rule
  - prefer_key_path # TODO: re-enable this rule
  - prefer_nimble
  - prefer_self_in_static_references # TODO: re-enable this rule
  - prefixed_toplevel_constant
  - redundant_self # TODO: Consider re-enabling either this rule or `explicit_self`
  - required_deinit
  - return_value_from_void_function # TODO: re-enable this rule
  - sorted_enum_cases
  - sorted_imports
  - superfluous_else
  - test_case_accessibility # TODO: re-enable this rule
  - todo
  - trailing_closure
  - type_contents_order
  - unneeded_escaping # TODO: Consider re-enabling this rule
  - unneeded_parentheses_in_closure_argument # TODO: Consider re-enabling this rule
  - unused_declaration # False positives on protocol-confirming methods
  - unused_parameter
  - vertical_whitespace_between_cases

cyclomatic_complexity:
  warning: 16

function_body_length:
  warning: 55

implicit_return:
  included:
    - closure

nesting:
  type_level:
    warning: 2

trailing_comma:
  mandatory_comma: true

file_header:
  required_pattern: |
    \/\/
    \/\/  (.+).swift
    \/\/  Authenticator
    \/\/
    \/\/  Copyright \(c\) (\d{4}|\d{4}-\d{4}) Authenticator authors
    \/\/
    \/\/  Permission is hereby granted, free of charge, to any person obtaining a copy
    \/\/  of this software and associated documentation files \(the "Software"\), to deal
    \/\/  in the Software without restriction, including without limitation the rights
    \/\/  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    \/\/  copies of the Software, and to permit persons to whom the Software is
    \/\/  furnished to do so, subject to the following conditions:
    \/\/
    \/\/  The above copyright notice and this permission notice shall be included in all
    \/\/  copies or substantial portions of the Software.
    \/\/
    \/\/  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    \/\/  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    \/\/  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    \/\/  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    \/\/  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    \/\/  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    \/\/  SOFTWARE.
    \/\/
