# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.4.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    carthage(
      use_submodules: true,
      no_build: true
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Authenticator")
  end

  desc "Submit a new beta build to TestFlight"
  lane :beta do
    # Ensure that the git repo is not dirty.
    ensure_git_status_clean

    # Increment the build number (not the version number).
    new_build_number = latest_testflight_build_number + 1
    increment_build_number(
      build_number: new_build_number
    )

    # Build the app with the Release configuration.
    gym(
      scheme: "Authenticator",
      clean: true
    )

    # Upload the new binary to TestFlight.
    pilot

    # Commit the updated build number.
    commit_version_bump(
      message: "Build #{new_build_number}",
      xcodeproj: "Authenticator.xcodeproj"
    )

    # Add a git tag for this build.
    add_git_tag
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # Generate updated screenshots.
    snapshot

    # Ensure that the git repo is not dirty.
    # This step will fail if the screenshots were not already up-to-date and committed.
    ensure_git_status_clean

    # Increment the build number (not the version number).
    new_build_number = latest_testflight_build_number + 1
    increment_build_number(
      build_number: new_build_number
    )

    # Build the app with the Release configuration.
    gym(
      scheme: "Authenticator",
      clean: true
    )

    # Upload the app metadata and binary to iTunes Connect.
    deliver(
      force: true
    )

    # Commit the updated build number.
    new_version_number = get_version_number
    commit_version_bump(
      message: "Release #{new_version_number}",
      xcodeproj: "Authenticator.xcodeproj"
    )

    # Add a git tag for this build.
    add_git_tag(
      tag: new_version_number
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
