# Configuration for Snapshot (https://fastlane.tools/snapshot)

workspace "Authenticator.xcworkspace"
scheme "Authenticator Demo"

devices([
  "iPhone SE",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X",
])

languages([
  "en-US",
])

clear_previous_screenshots true
skip_open_summary true
