# Configuration for Snapshot (https://fastlane.tools/snapshot)

scheme "Authenticator Demo"

devices([
  "iPhone 7",
  "iPhone 7 Plus",
  "iPhone SE",
])

languages([
  "en-US",
])

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones
